### ISSUE TITLE
Power LED stays blue

### ISSUE THREAD

**Issue by mmartain** [kszaq/OpenELEC.tv#12]
I use the HD18Q image and it is working great. 

The only issue is the power led. When i boot the box the led is off, and when the mxq logo appears, the led turns blue. Sadly, when the box goes into standby the led stays blue.

Sadly i don't have the knowledge or the resources to build these images myself.

The box i have is the OTT box.

**Comment by kszaq** [comment]
Can you do the following:
* boot into Android
* open Terminal Emulator or connect over ADB
* issue `cat /sys/kernel/debug/gpio` and post results here?

**Comment by mmartain** [comment]
I tried it on my box with android but got a permission denied. Then i tried it on the openelec box via putty and these were the results:


# cat /sys/kernel/debug/gpio
GPIOs 0-138:
 gpio-1   (power_led           ) out hi
 gpio-3   (gpio_key            ) in  hi
 gpio-49  (amlsd               ) in  hi
 gpio-137 (mute_spk            ) out lo

**Comment by kszaq** [comment]
This commands reads GPIO assignment and it has do be executed on manufacturer's firmware (i.e. Android) to get proper results. You need to be rooted to execute the command.

**Comment by cgg507** [comment]
Hey kszaq, I appreciate the effort you made to put this building together. I have a Vigica C100S (clone of Venz K1 I guess) which uses the AML S805. Everything is fine with the MXQ build but the Powered-Up/PowerOff LED (mine is dual color, blue/red). It works as expected when on (Blue), but when shutting Kodi down, it stays blue, rather than changing to red (or I dont mind if it gets off at all - No LED)

Here's my GPIO (from Android)

root@KI:/ # cat /sys/kernel/debug/gpio
GPIOs 0-138:
 gpio-3   (gpio_key            ) in  hi
 gpio-21  (sysfs               ) out hi
 gpio-22  (sysfs               ) out hi
 gpio-49  (amlsd               ) in  hi
 gpio-107 (sdio_wifi           ) out hi
 gpio-117 (bt_rfkill           ) out lo
 gpio-137 (mute_spk            ) out lo


while looking the filesystem i noticed these two files that may/maynot be helpful 
/system/bin/led_service
/dev/socket/led

Thanks in advance for your help and patience.

**Comment by kszaq** [comment]
@cgg507 It seems like your LED is managed by some kind of userspace driver as there is no pin for LED in GPIO assignement. There also may be some information about it in device tree if your device uses amlogic sysled driver.

**Comment by alepsrt** [comment]
Same problem, when the box goes into standby or shutdown the led stays blue.

cat /sys/kernel/debug/gpio:
GPIOs 0-138:
 gpio-3   (gpio_key            ) in  hi
 gpio-49  (amlsd               ) in  hi
 gpio-75  (bluetooth           ) in  l
 gpio-117 (bt_rfkill           ) out hi
 gpio-137 (mute_spk            ) out lo

With openelec-5.0 led worked fine, some suggestion?

**Comment by kszaq** [comment]
@alepsrt In recent builds LED management is off unless defined in device tree, like here:
https://github.com/kszaq/OpenELEC.tv/blob/openelec-7.0/projects/Amlogic/patches/linux/meson8b_mxq_dtd.patch#L923

I can't add LED definitions for one type of box as that would not work/work improperly on others. So with HD18Q power LED won't work unless it's managed by u-boot.

**Comment by sivanoff** [comment]
@kszaq in my case LED always red, gpio output almost same as alepsrt's. How can I figure out what should be added/changed in dtd file to be able to control color.

**Comment by kszaq** [comment]
In recent Amlogic kernels GPIO pins seem to be hardcoded by manufacturers. You need to get a source code from manufacturer to make it work.
